on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [3.07+2, 3.08.4, 3.09.3, 3.10.2, 3.11.2, 3.12.1, 4.00.1, 4.01.0, 4.02.3, 4.03.0, 4.04.2, 4.05.0, 4.06.1, 4.07.1, 4.08.1, 4.09.1, 4.10.2, 4.11.2, 4.12.1, 4.13.1, 4.14.1]
        camlp5-version: [6.04, 6.06, 6.07, 6.11, 6.12, 6.13, 6.14, 6.15, 6.16 6.17, 7.00, 7.01, 7.03, 7.05, 7.06, 7.06.10-g84ce6cc4 7.08, 7.09, 7.10, 7.11, 7.12, 7.13, 7.14, 8.00~alpha01 8.00~alpha02, 8.00~alpha03, 8.00~alpha04, 8.00~alpha05 8.00~alpha06, 8.00, 8.00.01, 8.00.02, 8.00.03, 8.00.04]
    runs-on: ubuntu-latest
    steps:
      - name: check out hol-light ...
        uses: actions/checkout@v2
      - name: set up cache ...
        uses: actions/cache@v2
        with:
          path: ~/.opam
          key: ${{ runner.os }}-ocaml-${{ matrix.ocaml-version }}
      - name: set up opam ...
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: install num ...
        run: opam install num
      - name: install ocamlfind ...
        run: opam install ocamlfind
      - name: install camlp5 ...
        run: opam install camlp5.${{ matrix.camlp5-version }}
      - name: setup hol-light ...
        run: |
          eval $(opam env)
          make
      - name: run test ...
        run: |
          eval $(opam env)
          echo "#use \"hol.ml\";;" | ocaml -I `camlp5 -where` camlp5o.cma
